name: Deploy Documentation

on:
  push:
    branches:
      - documentation
  pull_request:
    branches:
      - documentation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Dependencies
        run: |
          cd documentation
          npm install
      - name: Build Documentation
        run: |
          cd documentation
          npm run build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/documentation'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          publish_branch: gh-pages
      - name: Deploy Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          publish_branch: gh-pages-preview
          destination_dir: preview/${{ github.event.pull_request.number }} 